name: Editor tests
on:
  - pull_request
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ATOM_JASMINE_REPORTER: list

jobs:
  tests:
    name: tests
    if: |
      !startsWith(github.event.pull_request.title, '[skip-ci]') &&
      !startsWith(github.event.pull_request.title, '[skip-editor-ci]')
    strategy:
      matrix:
        # os: [ubuntu-20.04, macos-latest, windows-2019]
        os: [ubuntu-20.04, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 16

    - name: install dependencies
      run: yarn install

    - name: build dependencies
      run: yarn build

    - name: Run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: node script/run-tests.js spec
